source-list:
  - rtsp://localhost:8554/test

streammux:
  batch-size: 1
  batched-push-timeout: 40000
  width: 1920
  height: 1080

osd:
  process-mode: 0
  display-text: 0

tiler:
  rows: 1
  columns: 1
  width: 1280
  height: 720

sink:
  qos: 0
  type: 1
  rtsp_port: 8555
  udp_port: 5400
  mount: /ds-test

primary-gie:
  plugin-type: 0
  config-file-path: pgie_config.yml

roi:
  enabled: true
  x: 150
  y: 700
  w: 250
  h: 150